In [1]:
import numpy as np
import itertools

DESC:

In [2]:
# for an unkown function, take input cardinality and output cardinality, return a list of all possible functions

# should only take card in >/= card out to be deterministic
def generate_functions(card_in, card_out):
    # all possible outputs for each input
    all_possible_outputs = list(itertools.product(range(card_out), repeat=card_in))

    # creates a function for each possible output
    functions = []
    for outputs in all_possible_outputs:
        function = dict(zip(range(card_in), outputs)) # use dict or list?
        functions.append(function)

    return functions

In [16]:
# generate all combination of the functions
generate_functions(6, 2) # (2,2) -> {to0, id, swap, to1}

[{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0},
 {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 1},
 {0: 0, 1: 0, 2: 0, 3: 0, 4: 1, 5: 0},
 {0: 0, 1: 0, 2: 0, 3: 0, 4: 1, 5: 1},
 {0: 0, 1: 0, 2: 0, 3: 1, 4: 0, 5: 0},
 {0: 0, 1: 0, 2: 0, 3: 1, 4: 0, 5: 1},
 {0: 0, 1: 0, 2: 0, 3: 1, 4: 1, 5: 0},
 {0: 0, 1: 0, 2: 0, 3: 1, 4: 1, 5: 1},
 {0: 0, 1: 0, 2: 1, 3: 0, 4: 0, 5: 0},
 {0: 0, 1: 0, 2: 1, 3: 0, 4: 0, 5: 1},
 {0: 0, 1: 0, 2: 1, 3: 0, 4: 1, 5: 0},
 {0: 0, 1: 0, 2: 1, 3: 0, 4: 1, 5: 1},
 {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0},
 {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 1},
 {0: 0, 1: 0, 2: 1, 3: 1, 4: 1, 5: 0},
 {0: 0, 1: 0, 2: 1, 3: 1, 4: 1, 5: 1},
 {0: 0, 1: 1, 2: 0, 3: 0, 4: 0, 5: 0},
 {0: 0, 1: 1, 2: 0, 3: 0, 4: 0, 5: 1},
 {0: 0, 1: 1, 2: 0, 3: 0, 4: 1, 5: 0},
 {0: 0, 1: 1, 2: 0, 3: 0, 4: 1, 5: 1},
 {0: 0, 1: 1, 2: 0, 3: 1, 4: 0, 5: 0},
 {0: 0, 1: 1, 2: 0, 3: 1, 4: 0, 5: 1},
 {0: 0, 1: 1, 2: 0, 3: 1, 4: 1, 5: 0},
 {0: 0, 1: 1, 2: 0, 3: 1, 4: 1, 5: 1},
 {0: 0, 1: 1, 2: 1, 3: 0, 4: 0, 5: 0},
 {0: 0, 1: 1, 2: 1, 3: 0,

$\vec F_i = \begin{bmatrix} f_i(0) \\ f_i(1) \\ \vdots \\ f_i(m) \end{bmatrix} $

$\vec F = \left[ \vec F_1, \vec F_2, ... \vec F_n \right] = 
\left[ \begin{bmatrix} f_1(0) \\ f_1(1) \\ \vdots \\ f_1(m) \end{bmatrix}, \begin{bmatrix} f_2(0) \\ f_2(1) \\ \vdots \\ f_2(m) \end{bmatrix}, \dots \space \begin{bmatrix} f_n(0) \\ f_n(1) \\ \vdots \\ f_n(m) \end{bmatrix}\right] =  
\begin{bmatrix}
f_1(0) & f_2(0) & \dots & f_n(0) \\
f_1(1) & f_2(1) & \dots & f_n(1) \\
\vdots& \vdots& \ddots & \vdots \\
f_1(m) & f_2(m)& \dots & f_n(m)
\end{bmatrix}$

^matrix of functions generated

In [22]:
for hidden1_index, hidden1 in enumerate(generate_functions(2,2)):
    print(hidden1_index, hidden1)
    # if there's more hidden variables: ...
    #     for hidden2 in [generate_functions(2*2,2)]:
    #         print(hidden2)

    p_det = np.zeros((2,2,2,2)) # np.zeros(how many matrices, shape_vertical, shape_horitzontal, ...  , for each element, crete a matrices)

0 {0: 0, 1: 0}
1 {0: 0, 1: 1}
2 {0: 1, 1: 0}
3 {0: 1, 1: 1}


number of values = $\prod_i (\text{card in list}) \times \prod_j(\text{card out list})$


we create matrix of zeros s.t.

$\begin{bmatrix} *_1 & * \\ * & * \end{bmatrix} 
\longrightarrow *_1 = \begin{bmatrix} *_{11} & * \\ * & * \end{bmatrix} \longrightarrow *_{11} = 0 \text{ OR } 1$

In [8]:
### for the case of 1 hidden variable

# (list of cardinalities for input variables, list of cardinalities for output variables) -> zero matrices structrue
def zero_matrices(in_lst, out_lst):
    num_vals = np.prod(in_lst)*np.prod(out_lst) # total number of cells is the product of elements in the lists
    
    return np.zeros(num_vals).reshape(tuple(sum([in_lst, out_lst], [])))    # create matrix of zeros, reshape it to ??? 
                                                                            # tuple(sum([[1,2],[3,4]], [] )) needs explanation

zero_matrices([2,2], [2,2])

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

## Example generalized:

$\space$

In [17]:
m = zero_matrices([2],[2,2])
print("for the example")
print(m)

for the example
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [10]:
base_strategies = generate_functions(2,2)
all_strategies = list(itertools.product(base_strategies, repeat=2))

# we want to use these functions i.e. this strategy:
f_u, g_u = all_strategies[5]


print("we want relevant position to be = 1")
for submatrix in range(2): # 2 comes from cardinality of output variable
    (x,y) = (f_u[submatrix], g_u[f_u[submatrix]])
    m[submatrix][y,x] = 1
print(m)

we want relevant position to be = 1
[[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]


In [11]:
# now for example XY -> AB

m = zero_matrices([2,2],[2,2])
print("for the example")
print(m)

for the example
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [12]:
base_strategies = generate_functions(2,2)
all_strategies = list(itertools.product(base_strategies, repeat=2))

# we want to use these functions i.e. this strategy:
f_u, g_u = all_strategies[5]


print("we want relevant position to be = 1")
for submatrix in range(2): # 2 comes from cardinality of output variable
    (x,y) = (f_u[submatrix], g_u[f_u[submatrix]])
    m[submatrix][y,x] = 1
print(m)

we want relevant position to be = 1
[[[[1. 1.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [1. 1.]]]]


In [13]:
# the position will be


#[input for func] -> output for func
def f(input):
    return generate_functions(2,1)[0][input] #generate_functions(card_in, card_out)[always 0][input]

(x,y) = (f(0), f(1))

print(x,y)

0 0


In [14]:
# i: each funciton generated
for i in range(4**2):
    print(f"F{i+1} :", generate_functions(4,2)[i])
    # print(f"F{i+1}(0) = ", generate_functions(4,2)[i][0])

F1 : {0: 0, 1: 0, 2: 0, 3: 0}
F2 : {0: 0, 1: 0, 2: 0, 3: 1}
F3 : {0: 0, 1: 0, 2: 1, 3: 0}
F4 : {0: 0, 1: 0, 2: 1, 3: 1}
F5 : {0: 0, 1: 1, 2: 0, 3: 0}
F6 : {0: 0, 1: 1, 2: 0, 3: 1}
F7 : {0: 0, 1: 1, 2: 1, 3: 0}
F8 : {0: 0, 1: 1, 2: 1, 3: 1}
F9 : {0: 1, 1: 0, 2: 0, 3: 0}
F10 : {0: 1, 1: 0, 2: 0, 3: 1}
F11 : {0: 1, 1: 0, 2: 1, 3: 0}
F12 : {0: 1, 1: 0, 2: 1, 3: 1}
F13 : {0: 1, 1: 1, 2: 0, 3: 0}
F14 : {0: 1, 1: 1, 2: 0, 3: 1}
F15 : {0: 1, 1: 1, 2: 1, 3: 0}
F16 : {0: 1, 1: 1, 2: 1, 3: 1}


In [ ]:
def gen_top_matrix():
    ...