In [ ]:
import numpy as np
import itertools

# Seed for reproducibility
np.random.seed(29)

# Generate random probabilities for P(Z)
p_z = np.random.rand(2)

# Generate random probabilities for P(A|Z,H1), P(M|A,H2), P(Y|M,H1,H2)
# Simplified to P(A|Z), P(M|A), P(Y|M) for this example
p_a_given_z = np.random.rand(2, 2)  # For each value of Z, a distribution over A
p_m_given_a = np.random.rand(2, 2)  # For each value of A, a distribution over M
p_y_given_m = np.random.rand(2, 2)  # For each value of M, a distribution over Y

# Dictionary to hold the distribution
distribution = {}

# Iterate over all possible values of A, M, Y, Z to populate the distribution dictionary
for z, a, m, y in itertools.product([0, 1], repeat=4):
    # Compute the joint probability as P(Z)*P(A|Z)*P(M|A)*P(Y|M)
    p_amy_given_z = p_z[z] * p_a_given_z[z][a] * p_m_given_a[a][m] * p_y_given_m[m][y]
    distribution[(a, m, y, z)] = p_amy_given_z

# Normalize the distribution to ensure the probabilities sum to 1
total_prob = sum(distribution.values())
for key in distribution:
    distribution[key] /= total_prob

In [ ]:
distribution

In [ ]:
import numpy as np
import itertools

# Define the number of states for binary variables
states = [0, 1]

# Generate random conditional probabilities
# P(A|Z)
p_a_given_z = np.random.rand(2, 2)  # For each Z (0, 1), P(A=0|Z), P(A=1|Z)
p_a_given_z /= p_a_given_z.sum(axis=0, keepdims=True)  # Normalize

# P(M|A)
p_m_given_a = np.random.rand(2, 2)  # For each A (0, 1), P(M=0|A), P(M=1|A)
p_m_given_a /= p_m_given_a.sum(axis=0, keepdims=True)  # Normalize

# P(Y|M)
p_y_given_m = np.random.rand(2, 2)  # For each M (0, 1), P(Y=0|M), P(Y=1|M)
p_y_given_m /= p_y_given_m.sum(axis=0, keepdims=True)  # Normalize

# Generate the distribution P_{AMY|Z}
distribution = {}
for z in states:
    for a in states:
        for m in states:
            for y in states:
                # Calculate the joint probability
                p = p_a_given_z[a, z] * p_m_given_a[m, a] * p_y_given_m[y, m]
                # Store in the dictionary with keys as (a, m, y, z) tuples
                distribution[(a, m, y, z)] = round(p, 3)  # Round to 3 decimal places

distribution

In [ ]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Initialize dictionary to store the distribution
distribution = {}

# Generate probabilities for each combination of A, M, Y given Z
for z in [0, 1]:
    for a in [0, 1]:
        for m in [0, 1]:
            for y in [0, 1]:
                # Key format: (a, m, y, z)
                key = (a, m, y, z)
                
                # Assign a random probability for this combination
                distribution[key] = round(np.random.rand(), 3)

# Display the generated distribution
distribution

In [ ]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB

model = gp.Model()
P_AB_giv_XY = model.addMVar(shape=(2,2,2,2), vtype=GRB.CONTINUOUS, name="P_AB|XY", lb=3.999, ub=4.001)
model.update

# sum of the probabilities is 1
for x,y in np.ndindex(2,2):
    model.addConstr(P_AB_giv_XY[:, :, x, y].sum() == 1)
model.addConstr(P_AB_giv_XY.sum() == 4)


# independences:
for a,b,x,y in np.ndindex(2,2,2,2):
    #  X ⫫ Y so P(X) = P(X|Y)

    # X ⫫ Y |A
    # X ⫫ Y |B

    # A ⫫ Y |X
    # A ⫫ Y |Y
    # A ⫫ Y
        
    # B ⫫ X

    # writing all the constraints out:
    """
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[a,b,x,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[a,b,:,y].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[a,b,:,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[a,:,x,y].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[a,:,x,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[a,:,:,y].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[a,:,:,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,b,x,y].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,b,x,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,b,:,y].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,b,:,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,:,x,y].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,:,x,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,:,y,:].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY[:,:,:,y].sum())
    model.addConstr(P_ABXY[a,b,x,y].sum() == P_ABXY.sum())"""
    
model.optimize()

In [ ]:
import gurobipy as gp
from gurobipy import GRB

model = gp.Model()
P_ABXY = model.addMVar(size = (2,2,2,2), vtype=GRB.CONTINUOUS, name= "P_ABXY", ub=0, lb=1)


# Probability values
probabilities = {}
for s in range(2):
    for t in range(2):
        for a in range(2):
            for b in range(2):
                name = f"P({a}{b}|{s}{t})"
                probabilities[(a, b, s, t)] = model.addVar(vtype=GRB.CONTINUOUS, name=name, ub=4.001, lb=3.999)

# Total probability constraint
model.addConstr(gp.quicksum(probabilities[(a, b, s, t)] for a in range(2) for b in range(2) for s in range(2) for t in range(2)) == 1, "TotalProbability")

# Conditional independence constraints
model.addConstr(probabilities[(1, 0, 0, 1)] == probabilities[(1, 0, 1, 1)], "A_T")
model.addConstr(probabilities[(0, 1, 0, 1)] == probabilities[(0, 1, 1, 1)], "B_T")
model.addConstr(probabilities[(1, 0, 0, 0)] == probabilities[(1, 0, 1, 0)], "A_T|S")
model.addConstr(probabilities[(0, 1, 0, 0)] == probabilities[(0, 1, 1, 0)], "B_T|S")
model.addConstr(probabilities[(1, 0, 0, 1)] == probabilities[(1, 0, 0, 0)], "A_T|B")
model.addConstr(probabilities[(0, 1, 0, 1)] == probabilities[(0, 1, 0, 0)], "B_T|A")
model.addConstr(probabilities[(0, 0, 0, 1)] == probabilities[(0, 0, 0, 0)], "S_T|A")
model.addConstr(probabilities[(0, 0, 1, 1)] == probabilities[(0, 0, 1, 0)], "S_T|B")

# Decimal point restriction
for p in probabilities.values():
    model.addConstr(p * 1000 <= 999, "DecimalRestriction")

# Set objective (not really relevant for feasibility problems)
model.setObjective(0, GRB.MINIMIZE)

# Optimize model
model.optimize()

# Retrieve results
result = {}
for key, val in probabilities.items():
    result[key] = val.x


In [ ]:
from gurobipy import GRB, Model

# Initialize model
model = Model()

# Define variables
P_AB_giv_XY = model.addMVar(shape=(2, 2, 2, 2), vtype=GRB.CONTINUOUS, name="P_AB|XY", lb=0, ub=1)

# Constraint for sum to 1 for each XY combination
for x in range(2):
    for y in range(2):
        model.addConstr(P_AB_giv_XY[:, :, x, y].sum() == 1)

# Additional constraints based on conditional independences
# These would be based on the equations derived from the independence conditions
# For example, for (X ⊥ Y), you don't need an explicit constraint because this is a conditional probability
# For (A ⊥ Y | X), you'd set constraints that reflect this condition, which might look like equating certain sums
# This is complex and depends on your exact interpretation of the independences in probabilistic terms

# Since you're not optimizing for a specific outcome, you might set an arbitrary objective or none at all
model.setObjective(0, GRB.MAXIMIZE)

# Optimize model
model.optimize()

# Extract and print variables
solution = {tuple(index): var.x for index, var in np.ndenumerate(P_AB_giv_XY.X)}
print(solution)


In [ ]:
import numpy as np

def satisfies_conditional_independences(distribution):
    # Implement checks for each conditional independence
    # For example, for (A ⊥ Y), verify that P(A|Y=y) = P(A) for all A, Y
    return True

def generate_distribution():
    distribution = np.zeros((2, 2, 2, 2))
    
    # Variable to ensure sum equals 1 (or 1000 in terms of thousandths)
    total_sum = 1000
    
    # Generate the distribution
    for x, y in np.ndindex(2, 2):
        # This is a placeholder for the actual logic you'd use to assign values
        # ensuring they sum up to 1000 for each combination of X and Y
        # and respect the conditional independences
        remaining = total_sum
        for a,b in np.ndindex(2, 2):
            if remaining > 0:
                value = np.random.randint(0, remaining + 1)
                distribution[a, b, x, y] = value
                remaining -= value
    
        # Normalize to ensure the sum equals to 1000 for each XY
        distribution[:, :, x, y] /= distribution[:, :, x, y].sum() / total_sum

    # Verify if the generated distribution satisfies conditional independences
    if satisfies_conditional_independences(distribution):
        return distribution
    else:
        # If the distribution does not satisfy the conditions, try again
        return generate_distribution()

# Generate and print a valid distribution
valid_distribution = generate_distribution()
print(valid_distribution)


In [ ]:
import numpy as np
import time

# wrapper function to initiate and terminate if takes too long

def generate_distribution():
    # if takes more than 5 seconds, terminate


        def satisfies_conditional_independences(dist):
            # independence checks
            # X ⫫ Y
            if not np.allclose(dist.sum(axis=(0, 1)), dist.sum(axis=(0, 1, 2, 3))):
                return False
            
            return True

        def generate_distribution():
            dist = np.zeros((2, 2, 2, 2), dtype=int)
            
            for x,y in np.ndindex(2, 2):
                # Allocate integers that sum to 1000 for each XY combination
                remaining = 1000
                allocations = []
                for _ in range(3):  # First allocate for three probabilities
                    allocation = np.random.randint(0, remaining)
                    allocations.append(allocation)
                    remaining -= allocation
                
                allocations.append(remaining)  # Assign the remaining value to the last probability
                
                np.random.shuffle(allocations)  # Shuffle to avoid bias
                
                # Assign allocations to the distribution
                it = 0
                for a,b in np.ndindex(2, 2):
                    dist[a, b, x, y] = allocations[it]
                    it += 1

            if satisfies_conditional_independences(dist):
                return dist
            else:
                return generate_distribution()


        # generate a distribution and convert to probabilities w/ three decimal points
        fin_dist = generate_distribution() / 1000.0
        print(fin_dist)

In [7]:
import numpy as np
import time

def satisfies_conditional_independences(dist):
    # placeholder for independence checks
    # X ⫫ Y
    # if not np.allclose(dist.sum(axis=(0, 1)), dist.sum(axis=(0, 1, 2, 3))):
    #     return False
    
    return True

def try_generate_distribution(start_time, timeout=5):
    # check elapsed time
    if time.time() - start_time > timeout:
        print("Generation process took too long and was terminated.")
        return None  # Or raise an exception

    dist = np.zeros((2, 2, 2, 2), dtype=int)
    
    for x, y in np.ndindex(2, 2):
        # Allocate integers that sum to 1000 for each XY combination
        remaining = 1000
        allocations = []
        for _ in range(3):  # First allocate for three probabilities
            allocation = np.random.randint(0, remaining)
            allocations.append(allocation)
            remaining -= allocation
        
        allocations.append(remaining)  # Assign the remaining value to the last probability
        
        np.random.shuffle(allocations)  # Shuffle to avoid bias
        
        # Assign allocations to the distribution
        it = 0
        for a, b in np.ndindex(2, 2):
            dist[a, b, x, y] = allocations[it]
            it += 1

    if satisfies_conditional_independences(dist):
        return dist
    else:
        return try_generate_distribution(start_time, timeout)

def generate_distribution_with_timeout():
    start_time = time.time()
    dist = try_generate_distribution(start_time)
    if dist is not None:
        # Convert the distribution to probabilities with three decimal points
        fin_dist = dist / 1000.0
        print(fin_dist)
    else:
        print("Failed to generate a valid distribution within the time limit.")

generate_distribution_with_timeout()


[[[[0.885 0.252]
   [0.653 0.594]]

  [[0.001 0.003]
   [0.005 0.058]]]


 [[[0.111 0.009]
   [0.34  0.134]]

  [[0.003 0.736]
   [0.002 0.214]]]]
